Add custom random pitch range and toggle CVARs
ZDoom/gzdoom pull request #1613
Opened 2022-05-20 22:23 UTC by spaztron64

This PR adds three new console commands that allow the user to set a minimum and maximum range for the random sound pitch playback using the new min_pitch and max_pitch CVARs, and to enable/disable these custom ranges at any time with the snd_redefine_pitch CVAR.

2022-05-21 05:37 UTC, coelckers requested changes
Why did you make these CVARs non-persistent? IMO these should be saved to the config.

2022-05-21 06:47 UTC, spaztron64 commented
> Why did you make these CVARs non-persistent? IMO these should be saved to the config.

Truth be told, I don't know how to do that.

2022-05-21 07:06 UTC, alexey-lysiuk reviewed
The line right after the added CVARs has the answer. It's `CVAR_ARCHIVE | CVAR_GLOBALCONFIG` instead of `0`.

2022-05-21 08:04 UTC, spaztron64 commented
> The line right after the added CVARs has the answer. It's `CVAR_ARCHIVE | CVAR_GLOBALCONFIG` instead of `0`.

Alright, I've added that now.

2022-05-21 08:12 UTC, alexey-lysiuk requested changes

2022-05-21 08:12 UTC, alexey-lysiuk commented on src/common/audio/sound/s_soundinternal.h
> +	bool		snd_redefine_pitch = false;
These members aren’t used anywhere.

2022-05-21 08:12 UTC, alexey-lysiuk commented on src/common/audio/sound/s_sound.cpp
> +CVARD(Int, max_pitch, 20, CVAR_ARCHIVE | CVAR_GLOBALCONFIG, "minimum pitch")
Please add `snd_` prefix to these CVARs.

2022-05-21 09:23 UTC, alexey-lysiuk requested changes
Please undo useless change to `s_soundinternal.h`. Also, it would be nice to have consistent code formatting with spaces and curly brackets placement.

2022-05-21 11:12 UTC, spaztron64 commented
> Please undo useless change to `s_soundinternal.h`. Also, it would be nice to have consistent code formatting with spaces and curly brackets placement.

Ok I brought back the newline. Please do any other aesthetic changes yourself, I've already flooded this PR with too many commits.

2022-05-21 15:03 UTC, alexey-lysiuk commented
> Ok I brought back the newline.

There are still two changed files in this PR.

> Please do any other aesthetic changes yourself, I've already flooded this PR with too many commits.

Of course, it shouldn’t be merged as a bunch of commits. Usually, it’s a contributor's duty to make their changes pretty.

2022-05-26 10:21 UTC, lofcz commented
> > Please undo useless change to `s_soundinternal.h`. Also, it would be nice to have consistent code formatting with spaces and curly brackets placement.
> 
> Ok I brought back the newline. Please do any other aesthetic changes yourself, I've already flooded this PR with too many commits.

Feel free to squash your commits :)

2022-05-30 23:07 UTC, spaztron64 commented
Apologies for taking this long, it's been an extremely busy week and I didn't have access to my computers. I've now removed the offending commits that unnecessarily changed s_soundinternal.h.

2022-05-31 06:41 UTC, alexey-lysiuk commented
Sorry, but I see no reason to have three commits for such small thing. In particular, two of them are changing code from the first one.

2022-10-10 07:06 UTC, coelckers approved these changes

2022-10-10 07:07 UTC, coelckers requested changes
This still uses the same very broken way to randomize the pitch by using rand() & value with a value that isn't checked to be a proper bit mask. Should be 'rand() % snd_min_pitch', IMO. But then, the original pitch code may need changing as well...

2023-01-15 13:02 UTC, coelckers commented
Closing because none of this is really needed. The sound engine already has an alternative pitch definition much better suited for this.

2023-01-15 13:02 UTC, closed without merging