Add support for not localizing drawn text
ZDoom/gzdoom pull request #1836
Opened 2022-11-23 21:27 UTC by Gutawer

This also modifies menu text fields to use this feature, fixing a bug which happens if the user puts `$` as the first character in an input string.

I've made a best effort here to ensure that any C++ function that needs to not localize incoming text has this flag set, since the previous behaviour was a discrepancy between C++ `DrawText` and ZScript `DrawText`.

2022-11-23 23:56 UTC, coelckers requested changes
This is far too noisy.
I think it would have been better to let ParseDrawTextureTags set a different default for native and scripted to avoid changing this much code.

2022-11-25 13:52 UTC, Gutawer commented
Fair enough, I was debating which way I wanted to do it and eventually convinced myself on the side of ZScript-and-C++ consistency. I've now reworked it to add a flag to `ParseDrawTextureTags` which opts in to differences between scripted and native code.

2022-12-03 22:30 UTC, merged

2022-12-04 03:26 UTC, SanyaWaffles commented
This seems to have broken how menus work for me. I'm getting the lookup strings themselves, not the localized versions.

2022-12-04 04:32 UTC, MajorCooke commented
@SanyaWaffles 
I suggest you make an issue or report on the forums.