Add some logs during soundfont selection
ZDoom/gzdoom pull request #1968
Opened 2023-01-23 01:25 UTC by emawind84

It helps understand what soundfont is currently used

Changes made together with the following pull request
refs: https://github.com/ZDoom/ZMusic/pull/44

2023-01-23 01:29 UTC, CandiceJoy approved these changes
Looks good to me :)

2023-01-23 14:17 UTC, CandiceJoy requested changes
Need to make it compile first, though :P Missing an include perhaps?

2023-01-23 16:17 UTC, coelckers commented
#include "printf.h" should be added.

2023-01-24 01:48 UTC, emawind84 commented
my bad, I will fix it

2023-01-24 02:12 UTC, emawind84 commented
I can't build on my pc anymore getting this error
`[build] D:\documents\GitHub\gzdoom\src\common\objects\autosegs.h(126): error C2485: 'no_sanitize_address': unrecognized extended attribute [D:\documents\GitHub\gzdoom\build\src\zdoom.vcxproj]
`
I will just push the update and see if it build

2023-01-24 02:31 UTC, emawind84 commented
I guess VS2017 is not supported anymore, I can build fine with VS2019 though.

2023-01-24 02:32 UTC, CandiceJoy approved these changes
Changed to approved.

2023-01-24 12:18 UTC, madame-rachelle commented
> I guess VS2017 is not supported anymore, I can build fine with VS2019 though.

GZDoom almost always uses the latest VS C++ version when it becomes available. There is a brief period of time between release and when all developers have switched, but it is typically fairly short. I think a new version is due to come out at some point.

2023-01-24 12:19 UTC, merged