Exposed ForceLightning() to ZScript. And added the ability to change the sound lightning makes.
ZDoom/gzdoom pull request #1975
Opened 2023-01-28 04:33 UTC by inkoalawetrust

This PR exposes the ForceLightning function to ZScript. Allowing for ZScript code to create lightning strikes at will without the use of the Light_ForceLightning line special. This can be used to create custom thunderstorm code that does not rely on the conditions and RNG of the original lightning code. Like the example file attached below.

The PR also adds a LightningSound MAPINFO key, which can be used to define a custom sound for lightning strikes to play on the map. Such as for having different maps use different lightning sounds (e.g one map has nearby thunder, while the next has distant thunder).
It also adds a sound parameter to ForceLightning(), to allow thunder to play different sounds on a per-strike basis. By changing the `LightningSound` string of the lightning thinker. The default sound for the sound parameter is world/thunder. For the Light_ForceLightning special, the sound passed will be the levels' current LightningSound.

If the LightningSound MAPINFO key isn't used at all, then world/thunder will play as the default, maintaing backwards compatibility. Passing an empty string to the MAPINFO property or the ForceLightning() function will make the lightning produce no sound at all.

The example mod demonstrates several combinations of lightning behavior. MAP01 has stock lightning, no custom sounds or anything. MAP02 produces silent thunder by using an empty LightningSound property, MAP03 uses the Zombiemans' random sight sounds for thunder. And MAP04 uses an entirely custom lightning implementation that ignores the MAPINFO property for its' own sound, produces thunder more frequently, and stops when the player is dead.

[Lightning example.zip](https://github.com/ZDoom/gzdoom/files/10525304/Lightning.example.zip)

2023-01-28 05:32 UTC, CandiceJoy requested changes
I would recommend leaving the original DLightningThinker constructor and ForceLightning functions somewhat intact while doing this; specific suggestions attached.

2023-01-28 05:32 UTC, CandiceJoy commented on src/playsim/mapthinkers/a_lightning.cpp
> -void DLightningThinker::Construct()
I would highly recommend doing this instead (note that I don't know if the syntax is EXACTLY right, but you get the idea :P)
`inline void DLightningThinker::Construct() : DLightningThinkerConstruct("world/thunder"){}`

2023-01-28 05:32 UTC, CandiceJoy commented on src/playsim/mapthinkers/a_lightning.h
> -	void Construct();
Obviously, add definitions here to match earlier suggestions.

2023-01-28 05:32 UTC, CandiceJoy commented on src/g_levellocals.h
> -	void ForceLightning(int mode);
`inline void ForceLightning(int mode) { ForceLightning(mode, "world/thunder"); }`

2023-01-28 05:32 UTC, CandiceJoy commented on src/playsim/mapthinkers/a_lightning.cpp
> -void DLightningThinker::ForceLightning (int mode)
`inline void DLightningThinker::ForceLightning (int mode) { ForceLightning( mode, "world/thunder" ); }`

2023-01-28 05:32 UTC, CandiceJoy commented on src/playsim/mapthinkers/a_lightning.cpp
> -void FLevelLocals::ForceLightning (int mode)
`inline void FLevelLocals::ForceLightning(int mode){ ForceLightning(mode, "world/thunder"); }`

2023-01-28 05:32 UTC, CandiceJoy commented on src/playsim/mapthinkers/a_lightning.h
> -	void ForceLightning (int mode);
Obviously, add definitions here to match earlier suggestions.

2023-01-28 06:14 UTC, inkoalawetrust commented
I don't think the way the constructor is handled is too much of an issue, I basically based it on how DEarthquake does it, and that class also has way more variables than one. The changes to ForceLighting also aren't much of an issue IMO. Before this PR, the line special was the only place that used the function, and I've already changed that to handle the new changes. In fact, I kinda added the current handling of the thunder sound (As opposed to just replacing world/thunder with Level->LightningSound in the S_Sound call), because exposing ForceLightning to ZScript may potentially block adding that sound parameter in down the line.

2023-01-28 12:34 UTC, coelckers requested changes
Passing strings by value should be avoided, unless the function needs it to be mutable. Otherwise, pass by reference, this is far more efficient.
Also, make sure that the sound gets restored for old savegames.

2023-01-29 03:43 UTC, inkoalawetrust commented
Okay, I've made the fixes. I've also playtested the old savegame fix with a save I made on Hexens' MAP01 in GZDoom 4.7.1, and the fallback to the original hardcoded sound works.

I've also changed how the sound is handled by ForceLightning(). Now the lightning thinkers' sound is a temporary one that is played only once, and can be passed by the function before the thinker goes back to using the maps' LightningSound.

2023-12-26 13:07 UTC, inkoalawetrust commented
Well, is this going to be merged ? I've fixed the problem with the lightning sound not working on prior save games.

2024-01-05 16:35 UTC, merged