Export FScanner parser to ZScript as ScriptScanner
ZDoom/gzdoom pull request #2290
Opened 2023-12-08 19:17 UTC by Cacodemon345

This PR exposes the internal `FScanner` parser to ZScript as `ScriptScanner`.

`ScriptScanner`s are created with `Create` functions, and destroyed by calling `Destroy` (after which it must not be used). `SetPrependMessage` is used to set the message that will be prepended to the displayed error messages in case of failure. The rest of the exported functions work unchanged from their native counterparts.

2023-12-09 09:59 UTC, RicardoLuis0 requested changes

2023-12-09 09:59 UTC, RicardoLuis0 commented on src/common/engine/sc_man.cpp
> +
.

2023-12-09 10:00 UTC, RicardoLuis0 commented on src/common/engine/sc_man.cpp
> +
.

2023-12-09 14:59 UTC, Cacodemon345 commented on src/common/engine/sc_man.cpp
> +
Done.

2023-12-09 14:59 UTC, Cacodemon345 commented on src/common/engine/sc_man.cpp
> +}
Done.

2023-12-10 06:17 UTC, coelckers requested changes
Please rewrite this to not use multiple inheritance. A lot of ZScripts inner workings circumvent standard C++ logic that ensure type safety and this may easily end up trashing the pointer to such an object because it may not point to where you expect it anymore.

2023-12-10 12:53 UTC, Cacodemon345 commented
Done as requested.

2023-12-11 09:41 UTC, nashmuhandes commented
Please also provide a working example mod that showcases the usage of this feature.

2023-12-11 18:26 UTC, Cacodemon345 commented
[scriptparserexample.zip](https://github.com/ZDoom/gzdoom/files/13639574/scriptparserexample.zip)
[demoscpt.txt](https://github.com/ZDoom/gzdoom/files/13639577/demoscpt.txt)

Here's one. Run GZDoom with the ZIP file and the uploaded `demoscpt.txt` lump and open any kind of map. It will print `1337` to console.

[demoscpt.txt](https://github.com/ZDoom/gzdoom/files/13639602/demoscpt.txt)

Since this example uses MustGetStringName function, it will abort to the console with the second one.

2023-12-25 09:55 UTC, coelckers commented
I merged this manually and changed it to use direct native calls for most functions

2023-12-25 09:55 UTC, closed without merging