Reworked client network state handling
ZDoom/gzdoom pull request #2542
Opened 2024-04-28 02:30 UTC by Boondorl

Currently working with client-side prediction is a bit too limiting due to the nature of only having the info that the client is predicting and nothing else. Not only this, but handling the prediction state via `cheats` is volatile as it allows players to unset it (likely unintentionally) while predicting which will break the game state immediately.

Prediction is now locked behind `ClientState` which is readonly. This will be used for getting a client's network status (both the consoleplayer and others) and currently supports `CS_PREDICTING`, `CS_LATEST_TICK`, and `CS_RUBBERBANDING`. `CS_LATEST_TICK` is of particular interest because it can allow effects and sounds to be executed on the player's last "real" tick rather than constantly being repredicted. This allows for things like sounds on landing to be played at the last predicted tick without rapid firing when being played back.

`ClientTic` has also been added which can be compared against `gametic` to see how far ahead the player is currently predicting on a given tick. Note that `gametic` becomes one tick ahead when predicting since its value is incremented after all game logic but before prediction starts.

These fields should mainly be used for client-side prediction as they won't give the same values across clients (similar to `consoleplayer`), but things like `CS_LATEST_TICK` and `ClientTic` are still set for all clients so logic can execute correctly on their end. For instance, a non-consoleplayer client will only update on a real tick, but their flag will always be set to `CS_LATEST_TICK` so a landing sound would still play at the correct time if checking against it.

2024-04-28 06:17 UTC, coelckers requested changes
Please make IsPredicting inline. This function gets called in performance critical code and it's a real call that's easily avoided.

2024-05-20 14:01 UTC, inkoalawetrust commented
So CF_PREDICTING is just a total dud now? Isn't that bad for compatibility with mods that might rely on the old client prediction handling, like mods that are no longer in development to be changed to use IsPredicting() instead? Might be a good idea to have CF_PREDICTING still be set and unset somewhere for backwards compatibility.

2024-05-20 15:28 UTC, Boondorl commented
It does still get set. As someone who's written a lot of client-side safe code, I'm fully aware it can't be tossed.

2024-05-20 18:10 UTC, inkoalawetrust commented
Oh my bad, I didn't see the line where it still gets switched on and off.

2024-06-28 08:07 UTC, Boondorl commented
With 4.13 looming, gonna close this for now since it'll need to be re-structured anyway for the prediction overhaul

2024-06-28 08:07 UTC, closed without merging