Tweak KEX/Unity order in IWAD selection box to be consistent across games
ZDoom/gzdoom pull request #2772
Opened 2024-10-19 11:31 UTC by Calinou

- Fix missing space in "Hacx: Twitch 'n Kill".
  - The official capitalization seems a bit inconsistent with ["HacX" being regularly used by its original developers](http://www.drnostromo.com/hacx/), but [the Doom wiki uses "Hacx"](https://doomwiki.org/wiki/Hacx).

___

- See https://github.com/ZDoom/gzdoom/issues/2669#issuecomment-2291320473.

2024-10-19 11:58 UTC, madame-rachelle commented
Er, What consistency is this adhering to?

2024-10-19 11:59 UTC, madame-rachelle requested changes
See my comment in the main thread

2024-10-19 13:07 UTC, coelckers commented
> Er, What consistency is this adhering to?

Is this so hard to see? For the Final Doom WADs, KEX comes after Unity, but for Doom 1 and 2 it comes after.

2024-10-22 04:49 UTC, madame-rachelle commented
I don't like this order. The Kex edition came after the Unity editions did, so I will handle this myself.

The original came from an external contribution.

2024-10-22 04:49 UTC, closed without merging